package link.socket.ampere.agents.domain.reasoning

import kotlinx.serialization.Serializable
import link.socket.ampere.agents.domain.expectation.Expectations
import link.socket.ampere.agents.domain.task.Task
import link.socket.ampere.agents.events.meetings.Meeting
import link.socket.ampere.agents.events.tickets.Ticket
import link.socket.ampere.agents.events.utils.generateUUID

typealias PlanId = String

/**
 * Represents a high-level plan produced by an agent for any given type of task.
 */
@Serializable
sealed interface Plan {

    /** Unique identifier for the plan. */
    val id: PlanId

    /** Ordered list of steps the agent intends to take. */
    val tasks: List<Task>

    /** A rough, relative measure of complexity (e.g., 1–10). */
    val estimatedComplexity: Int

    /** A set of expectations the agent expects to be met during execution. */
    val expectations: Expectations

    /**
     * Whether the planner asked for a person before this plan is carried out.
     *
     * The planning prompt asks the model for this as a yes/no alongside the
     * steps, so it is the planner's own self-report (in the sense of
     * [ConfidenceSource.SELF_REPORTED]) and never a measured judgment. A plan
     * that was not generated by a model — [Blank], a fallback plan, one built
     * by hand — reports `false`: nothing asked.
     *
     * A consumer that gates a write on the plan (AMPR-385 H1) reads this to
     * decide whether to show the plan to a person first.
     */
    val requiresHumanInput: Boolean

    @Serializable
    data object Blank : Plan {
        override val id: PlanId = ""
        override val tasks: List<Task> = emptyList()
        override val estimatedComplexity: Int = 0
        override val expectations: Expectations = Expectations.blank
        override val requiresHumanInput: Boolean = false
    }

    @Serializable
    data class ForIdea(
        val idea: Idea,
        override val tasks: List<Task> = emptyList(),
        override val estimatedComplexity: Int = 0,
        override val expectations: Expectations = Expectations.blank,
        override val requiresHumanInput: Boolean = false,
    ) : Plan {

        override val id: PlanId =
            generateUUID(idea.id)
    }

    @Serializable
    data class ForMeeting(
        val meeting: Meeting,
        override val tasks: List<Task> = emptyList(),
        override val estimatedComplexity: Int = 0,
        override val expectations: Expectations = Expectations.blank,
        override val requiresHumanInput: Boolean = false,
    ) : Plan {

        override val id: PlanId =
            generateUUID(meeting.id)
    }

    @Serializable
    data class ForTask(
        val task: Task,
        override val tasks: List<Task> = emptyList(),
        override val estimatedComplexity: Int = 0,
        override val expectations: Expectations = Expectations.blank,
        override val requiresHumanInput: Boolean = false,
    ) : Plan {

        override val id: PlanId =
            generateUUID(task.id)
    }

    @Serializable
    data class ForTicket(
        val ticket: Ticket,
        override val tasks: List<Task> = emptyList(),
        override val estimatedComplexity: Int = 0,
        override val expectations: Expectations = Expectations.blank,
        override val requiresHumanInput: Boolean = false,
    ) : Plan {

        override val id: PlanId =
            generateUUID(ticket.id)
    }

    companion object {
        val blank: Plan = Blank
    }
}
