#!/usr/bin/env bash
# Run the ampere CLI.
# Any arguments are forwarded to the CLI.

if [ $# -eq 0 ]; then
    ./gradlew --quiet ":ampere-cli:runJvm"
else
    ./gradlew --quiet ":ampere-cli:runJvm" --args="$*"
fi
