package link.socket.ampere.agents.domain.routing.local

import kotlinx.serialization.Serializable
import link.socket.ampere.agents.domain.routing.capability.ModelDescriptorRegistry
import link.socket.ampere.agents.domain.routing.capability.executesLocally
import link.socket.ampere.domain.ai.provider.AIProvider_OnDevice
import link.socket.ampere.domain.ai.provider.ProviderId

/**
 * Where a model call ran (AMPR-327).
 *
 * Two values on purpose. "On-device" is a claim a person relies on — that the
 * prompt did not leave the hardware in their hand — so anything that is not
 * provably [ON_DEVICE] is [CLOUD], including Apple's Private Cloud Compute
 * models, which run on Apple's servers however strong their privacy guarantees.
 * A third locality for those is a deliberate future decision, not something to
 * fold into this one.
 */
@Serializable
enum class InferenceLocality {
    /** Generated by a [LocalInferenceEngine] on this device. Nothing left it. */
    ON_DEVICE,

    /** Generated by a provider reached over the network. */
    CLOUD,
}

/**
 * Decides the [InferenceLocality] of a call from the provider and model that
 * served it — the two facts every
 * [TelemetryEvent][link.socket.ampere.agents.domain.event.TelemetryEvent] carries.
 *
 * `suspend` because the catalog it usually consults
 * ([ModelDescriptorRegistry]) is mutex-guarded.
 */
fun interface InferenceLocalityClassifier {
    suspend fun localityOf(providerId: ProviderId, modelId: String): InferenceLocality
}

/**
 * Classifies by the catalog alone: a model whose descriptor
 * [executesLocally][link.socket.ampere.agents.domain.routing.capability.executesLocally]
 * is [InferenceLocality.ON_DEVICE].
 *
 * A model the catalog cannot describe falls back to its provider id, so an
 * on-device call is still recognised after a catalog refresh that dropped its
 * descriptor. Anything else unknown is [InferenceLocality.CLOUD] — the safe
 * direction for a privacy label.
 *
 * This answers "what does the catalog say about this model", not "what ran".
 * A host that holds the executing client should prefer it as the classifier:
 * [link.socket.ampere.llm.DispatchingUpstreamLlmClient] also knows whether an
 * engine is bound, which the catalog cannot.
 */
class CatalogLocalityClassifier(
    private val registry: ModelDescriptorRegistry,
) : InferenceLocalityClassifier {

    override suspend fun localityOf(providerId: ProviderId, modelId: String): InferenceLocality {
        val descriptor = registry.descriptorFor(modelId)
        val local = descriptor?.executesLocally ?: (providerId == AIProvider_OnDevice.id)
        return if (local) InferenceLocality.ON_DEVICE else InferenceLocality.CLOUD
    }
}
