package link.socket.ampere.agents.definition

import java.util.concurrent.CopyOnWriteArrayList
import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue
import kotlinx.coroutines.runBlocking
import kotlinx.datetime.Clock
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import link.socket.ampere.agents.config.AgentActionAutonomy
import link.socket.ampere.agents.definition.code.CodeState
import link.socket.ampere.agents.domain.cognition.CognitiveAffinity
import link.socket.ampere.agents.domain.outcome.ExecutionOutcome
import link.socket.ampere.agents.domain.reasoning.Plan
import link.socket.ampere.agents.domain.status.TaskStatus
import link.socket.ampere.agents.domain.task.Task
import link.socket.ampere.agents.execution.ParameterStrategy
import link.socket.ampere.agents.execution.detailText
import link.socket.ampere.agents.execution.executor.FunctionExecutor
import link.socket.ampere.agents.execution.priorResultsSection
import link.socket.ampere.agents.execution.request.ExecutionContext
import link.socket.ampere.agents.execution.request.ExecutionRequest
import link.socket.ampere.agents.execution.tools.FunctionTool
import link.socket.ampere.agents.execution.tools.Tool
import link.socket.ampere.domain.ai.configuration.AIConfiguration_Default
import link.socket.ampere.domain.ai.model.AIModel_Claude
import link.socket.ampere.domain.ai.provider.AIProvider_Anthropic

/**
 * AMPR-408, the whole chain: a two-tool plan where the second tool's *generated
 * parameters* carry text from the first tool's result.
 *
 * This is the case the bug made impossible. The plan walk
 * ([AutonomousAgent.executePlan]) dispatches one step at a time, each step's
 * parameters are generated by a model call the tool's [ParameterStrategy] prompts
 * for, and that prompt was built from the step's own description and nothing else —
 * so "search for X, then summarise what you found" generated the summary step's
 * parameters with no idea what the search returned.
 *
 * The agent is built with a real [FunctionExecutor] and a real
 * `ToolExecutionEngine` rather than a mocked `onToolExecution`, because the
 * parameter-generating model call is the thing under test. The fake model is an
 * echo: it copies the earlier result out of the prompt it is given, which is how a
 * generated *parameter* — not merely a prompt — can be asserted on without a
 * provider.
 */
class PlanStepPriorResultsTest {

    private companion object {
        const val SEARCH_TOOL = "search_notes"
        const val SUMMARISE_TOOL = "summarise_notes"

        /** What the first step "finds". Nothing but step one's result can supply it. */
        const val LAUNCH_FACT = "the launch slipped to Thursday"

        const val NOTHING_EARLIER = "nothing earlier to use"
    }

    private val prompts = CopyOnWriteArrayList<String>()
    private val summariseParameters = CopyOnWriteArrayList<String>()
    private val dispatchedToSummarise = CopyOnWriteArrayList<ExecutionRequest<*>>()

    @Test
    fun `the second step's generated parameters carry text from the first step's result`() {
        val agent = agent()

        val outcome = runBlocking { agent.executePlan(twoStepPlan()) }

        assertTrue(outcome is ExecutionOutcome.Success, "got ${outcome::class.simpleName}")
        assertEquals(1, summariseParameters.size, "the second step ran exactly once")
        assertContains(
            summariseParameters.single(),
            LAUNCH_FACT,
            message = "the summary step's generated parameters have to carry what the search step found",
        )
    }

    @Test
    fun `the second step's parameter prompt names the first step and its result`() {
        val agent = agent()

        runBlocking { agent.executePlan(twoStepPlan()) }

        assertEquals(2, prompts.size, "one parameter-generation call per step")
        val summarisePrompt = prompts.last()
        assertContains(summarisePrompt, "search the notes for the launch date")
        assertContains(summarisePrompt, LAUNCH_FACT)
    }

    @Test
    fun `the first step's prompt carries no prior results because nothing ran before it`() {
        val agent = agent()

        runBlocking { agent.executePlan(twoStepPlan()) }

        assertFalse(
            prompts.first().contains("Results of the steps already executed"),
            "a plan's first step asks exactly the question it asked before AMPR-408",
        )
    }

    @Test
    fun `the request the second tool is dispatched with carries the first step's outcome`() {
        val agent = agent()

        runBlocking { agent.executePlan(twoStepPlan()) }

        val carried = dispatchedToSummarise.single().priorResults
        assertEquals(1, carried.size, "one step ran before this one")
        assertContains(carried.single().stepDescription, "search the notes")
        assertContains(
            carried.single().detailText(),
            LAUNCH_FACT,
            message = "the carried result is the step's own report, not the one-step plan's " +
                "tally of it — a tally is what the next step used to be handed",
        )
    }

    private fun twoStepPlan(): Plan.ForTask = Plan.ForTask(
        task = Task.CodeChange(
            id = "parent-task",
            status = TaskStatus.Pending,
            description = "find out when the launch is and summarise it",
        ),
        tasks = listOf(
            Task.CodeChange(
                id = "step-1",
                status = TaskStatus.Pending,
                description = "search the notes for the launch date",
                toolId = SEARCH_TOOL,
            ),
            Task.CodeChange(
                id = "step-2",
                status = TaskStatus.Pending,
                description = "summarise what you found",
                toolId = SUMMARISE_TOOL,
            ),
        ),
        estimatedComplexity = 2,
    )

    private fun agent(): SparkBasedAgent<CodeState> = SparkBasedAgent(
        agentId = "prior-results-agent",
        cognitiveAffinity = CognitiveAffinity.ANALYTICAL,
        initialState = CodeState.blank,
        _additionalTools = setOf(searchTool(), summariseTool()),
        _aiConfiguration = AIConfiguration_Default(
            provider = AIProvider_Anthropic,
            model = AIModel_Claude.Sonnet_5,
        ),
        _llmProvider = { prompt -> echoingModel(prompt) },
        _executor = FunctionExecutor.create(),
    )

    /**
     * A model that quotes back the one line of its prompt that carries an earlier
     * step's result, or says there was none.
     *
     * Deliberately not a canned response: a fixed string would pass whether or not
     * the prompt contained the earlier result, which is the whole question.
     */
    private fun echoingModel(prompt: String): String {
        prompts += prompt
        val quoted = prompt.lines()
            .map { it.trim() }
            .firstOrNull { it.contains(LAUNCH_FACT) }
            ?: NOTHING_EARLIER
        return """{"summary": "$quoted"}"""
    }

    /** Step one: returns the fact nothing else in the test can supply. */
    private fun searchTool(): FunctionTool<ExecutionContext.NoChanges> = FunctionTool(
        id = SEARCH_TOOL,
        name = "Search Notes",
        description = "searches the notes",
        requiredAgentAutonomy = AgentActionAutonomy.FULLY_AUTONOMOUS,
        parameterStrategy = EchoingStrategy(),
        executionFunction = { request ->
            succeed(request, message = LAUNCH_FACT)
        },
    )

    /** Step two: records the parameters it was handed. */
    private fun summariseTool(): FunctionTool<ExecutionContext.NoChanges> = FunctionTool(
        id = SUMMARISE_TOOL,
        name = "Summarise Notes",
        description = "summarises what an earlier step found",
        requiredAgentAutonomy = AgentActionAutonomy.FULLY_AUTONOMOUS,
        parameterStrategy = EchoingStrategy(),
        executionFunction = { request ->
            summariseParameters += request.context.instructions
            dispatchedToSummarise += request
            succeed(request, message = "summarised")
        },
    )

    private fun succeed(request: ExecutionRequest<*>, message: String): ExecutionOutcome {
        val now = Clock.System.now()
        return ExecutionOutcome.NoChanges.Success(
            executorId = request.context.executorId,
            ticketId = request.context.ticket.id,
            taskId = request.context.task.id,
            executionStartTimestamp = now,
            executionEndTimestamp = now,
            message = message,
        )
    }

    /**
     * A strategy shaped like the real ones: it renders the earlier steps' results
     * into its prompt through the shared [priorResultsSection], and it rebuilds the
     * request from scratch to carry its generated parameters.
     */
    private class EchoingStrategy : ParameterStrategy {

        override fun buildPrompt(
            tool: Tool<*>,
            request: ExecutionRequest<*>,
            intent: String,
        ): String = listOf(
            "Generate parameters for ${tool.id}.",
            "Intent: $intent",
            priorResultsSection(request.priorResults),
            """Respond with {"summary": "<one line>"} and nothing else.""",
        ).filter { it.isNotBlank() }.joinToString("\n\n")

        override fun parseAndEnrichRequest(
            jsonResponse: String,
            originalRequest: ExecutionRequest<*>,
        ): ExecutionRequest<*> {
            val summary = Json.parseToJsonElement(jsonResponse)
                .jsonObject["summary"]
                ?.jsonPrimitive
                ?.content
                .orEmpty()

            return ExecutionRequest(
                context = ExecutionContext.NoChanges(
                    executorId = originalRequest.context.executorId,
                    ticket = originalRequest.context.ticket,
                    task = originalRequest.context.task,
                    instructions = summary,
                ),
                constraints = originalRequest.constraints,
            )
        }
    }
}
